# Exemple d'un config.yaml :
journald:
  unit: ssh
  follow: true

detection:
  threshold: 5                  # Valeur du seuil de détection
  window_seconds: 120           # Valeur en secondes pour la fenêtre de détection (Mode --once : va analyser les dernières 120 secondes)

db:
  host: "${DB_HOST}"
  user: "${DB_USER}"
  database: "${DB_NAME}"

host:
  adresse_mac: "00:00:00:00:00:00"
  adresse_ip: "127.0.0.1"
  os: "Debian 13"